services:
  - type: web
    name: flask-seo-audit
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: "."
    healthCheckPath: /